// IAU-Sternbild-Kürzel → Name. Lateinischer Name plus (wo gebräuchlich)
// deutscher Name, damit die Auswahl gut lesbar ist.
export const CONSTELLATIONS = {
  And: 'Andromeda',
  Ant: 'Antlia (Luftpumpe)',
  Aps: 'Apus (Paradiesvogel)',
  Aql: 'Aquila (Adler)',
  Aqr: 'Aquarius (Wassermann)',
  Ara: 'Ara (Altar)',
  Ari: 'Aries (Widder)',
  Aur: 'Auriga (Fuhrmann)',
  Boo: 'Boötes (Bärenhüter)',
  CMa: 'Canis Major (Großer Hund)',
  CMi: 'Canis Minor (Kleiner Hund)',
  CVn: 'Canes Venatici (Jagdhunde)',
  Cae: 'Caelum (Grabstichel)',
  Cam: 'Camelopardalis (Giraffe)',
  Cap: 'Capricornus (Steinbock)',
  Car: 'Carina (Kiel des Schiffs)',
  Cas: 'Cassiopeia',
  Cen: 'Centaurus (Zentaur)',
  Cep: 'Cepheus',
  Cet: 'Cetus (Walfisch)',
  Cha: 'Chamaeleon',
  Cir: 'Circinus (Zirkel)',
  Cnc: 'Cancer (Krebs)',
  Col: 'Columba (Taube)',
  Com: 'Coma Berenices (Haar der Berenike)',
  CrA: 'Corona Australis (Südliche Krone)',
  CrB: 'Corona Borealis (Nördliche Krone)',
  Crt: 'Crater (Becher)',
  Cru: 'Crux (Kreuz des Südens)',
  Crv: 'Corvus (Rabe)',
  Cyg: 'Cygnus (Schwan)',
  Del: 'Delphinus (Delfin)',
  Dor: 'Dorado (Schwertfisch)',
  Dra: 'Draco (Drache)',
  Equ: 'Equuleus (Füllen)',
  Eri: 'Eridanus (Fluss)',
  For: 'Fornax (Chemischer Ofen)',
  Gem: 'Gemini (Zwillinge)',
  Gru: 'Grus (Kranich)',
  Her: 'Hercules',
  Hor: 'Horologium (Pendeluhr)',
  Hya: 'Hydra (Wasserschlange)',
  Hyi: 'Hydrus (Kleine Wasserschlange)',
  Ind: 'Indus (Indianer)',
  LMi: 'Leo Minor (Kleiner Löwe)',
  Lac: 'Lacerta (Eidechse)',
  Leo: 'Leo (Löwe)',
  Lep: 'Lepus (Hase)',
  Lib: 'Libra (Waage)',
  Lup: 'Lupus (Wolf)',
  Lyn: 'Lynx (Luchs)',
  Lyr: 'Lyra (Leier)',
  Men: 'Mensa (Tafelberg)',
  Mic: 'Microscopium (Mikroskop)',
  Mon: 'Monoceros (Einhorn)',
  Mus: 'Musca (Fliege)',
  Nor: 'Norma (Winkelmaß)',
  Oct: 'Octans (Oktant)',
  Oph: 'Ophiuchus (Schlangenträger)',
  Ori: 'Orion',
  Pav: 'Pavo (Pfau)',
  Peg: 'Pegasus',
  Per: 'Perseus',
  Phe: 'Phoenix',
  Pic: 'Pictor (Maler)',
  PsA: 'Piscis Austrinus (Südlicher Fisch)',
  Psc: 'Pisces (Fische)',
  Pup: 'Puppis (Achterdeck)',
  Pyx: 'Pyxis (Schiffskompass)',
  Ret: 'Reticulum (Netz)',
  Scl: 'Sculptor (Bildhauer)',
  Sco: 'Scorpius (Skorpion)',
  Sct: 'Scutum (Schild)',
  Ser: 'Serpens (Schlange)',
  Sex: 'Sextans (Sextant)',
  Sge: 'Sagitta (Pfeil)',
  Sgr: 'Sagittarius (Schütze)',
  Tau: 'Taurus (Stier)',
  Tel: 'Telescopium (Fernrohr)',
  TrA: 'Triangulum Australe (Südl. Dreieck)',
  Tri: 'Triangulum (Dreieck)',
  Tuc: 'Tucana (Tukan)',
  UMa: 'Ursa Major (Großer Bär)',
  UMi: 'Ursa Minor (Kleiner Bär)',
  Vel: 'Vela (Segel des Schiffs)',
  Vir: 'Virgo (Jungfrau)',
  Vol: 'Volans (Fliegender Fisch)',
  Vul: 'Vulpecula (Füchschen)',
}

export function constellationName(abbr) {
  return CONSTELLATIONS[abbr] || abbr || 'Unbekannt'
}
